### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED issue on generation

### ISSUE THREAD

**Issue by elabz** [cbh123/charl-e-original#11]
Getting SSL error exception. Any pointers on getting past this? Thanks a million!
 

`[2960] Failed to execute script 'txt2img' due to unhandled exception!
File "kornia/feature/integrated.py", line 65, in LAFDescriptor File "kornia/feature/hardnet.py", line 66, in __init__ File "torch/hub.py", line 727, in load_state_dict_from_url File "torch/hub.py", line 593, in download_url_to_file File "urllib/request.py", line 216, in urlopen File "urllib/request.py", line 519, in open File "urllib/request.py", line 536, in _open File "urllib/request.py", line 496, in _call_chain File "urllib/request.py", line 1391, in https_open File "urllib/request.py", line 1351, in do_open urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module File "kornia/augmentation/__init__.py", line 43, in <module> File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
Traceback (most recent call last): File "urllib/request.py", line 1348, in do_open
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /Users/boss/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth
torch/_jit_internal.py:751: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x28836b760>. warnings.warn(f"Unable to retrieve source for @torch.jit._overload function: {func}.")
torch/_jit_internal.py:751: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x28836b5b0>. warnings.warn(f"Unable to retrieve source for @torch.jit._overload function: {func}.")
torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
[2953] WARNING: file already exists but should not: /var/folders/m5/y87htcw15jj4bw7m2zql8jjw0000gn/T/_MEInpMGBn/torch/_dl.cpython-310-darwin.so
[2953] WARNING: file already exists but should not: /var/folders/m5/y87htcw15jj4bw7m2zql8jjw0000gn/T/_MEInpMGBn/torch/_C_flatbuffer.cpython-310-darwin.so
[2953] WARNING: file already exists but should not: /var/folders/m5/y87htcw15jj4bw7m2zql8jjw0000gn/T/_MEInpMGBn/torch/_C.cpython-310-darwin.so
[2953] WARNING: file already exists but should not: /var/folders/m5/y87htcw15jj4bw7m2zql8jjw0000gn/T/_MEInpMGBn/pyarrow/lib.cpython-310-darwin.so`

**Comment by elabz** [comment]
I ended up manually downloading `https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth` and moving it to `~/.cache/torch/hub/checkpoints/` - seems to work just find now
